SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE IF NOT EXISTS `murphy_clothes` (
  `charid` int(11) NOT NULL,
  `clothes` LONGTEXT NOT NULL DEFAULT '',
  `outfit_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `murphy_outfits` (
  `charid` int(11) NOT NULL,
  `outfit_id` int(11) NOT NULL,
  `price` float(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `clothes` LONGTEXT NOT NULL DEFAULT '',
  `singleitems` LONGTEXT NOT NULL DEFAULT '',
  `gender` varchar(200) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `murphy_wearable` (
  `charid` int(11) NOT NULL,
  `outfit_id` int(11) NOT NULL,
  `skin` LONGTEXT NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Change charset for existing tables
ALTER TABLE `murphy_clothes` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `murphy_outfits` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `murphy_wearable` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;