    -- camping camp items
    ['camptent']        = {['name'] = 'camptent',        ['label'] = 'Camping Tent',    ['weight'] = 1000, ['type'] = 'item', ['image'] = 'camptent.png',        ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Campsite Item'},
    ['camphitchpost']   = {['name'] = 'camphitchpost',   ['label'] = 'Hitching Post',   ['weight'] = 1000, ['type'] = 'item', ['image'] = 'camphitchpost.png',   ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Campsite Item'},
    ['campcookstation'] = {['name'] = 'campcookstation', ['label'] = 'Cooking Station', ['weight'] = 1000, ['type'] = 'item', ['image'] = 'campcookstation.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Campsite Item'},
    ['camptorch']       = {['name'] = 'camptorch',       ['label'] = 'Campsite Torch',  ['weight'] = 500,  ['type'] = 'item', ['image'] = 'camptorch.png',       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Campsite Item'},
    ['campcrafting']    = {['name'] = 'campcrafting',    ['label'] = 'Camp Crafting',   ['weight'] = 1000, ['type'] = 'item', ['image'] = 'campcrafting.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Campsite Item'},
    ['campmoonshine']   = {['name'] = 'campmoonshine',   ['label'] = 'Camp Moonshine',  ['weight'] = 1000, ['type'] = 'item', ['image'] = 'campmoonshine.png',   ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Campsite Item'},

    -- moonshine
    ['moonshine'] = {['name'] = 'moonshine', ['label'] = 'Moonshine', ['weight'] = 300,  ['type'] = 'item', ['image'] = 'moonshine.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Jug of Moonshine'},
    ['yeast']     = {['name'] = 'yeast',     ['label'] = 'Yeast',     ['weight'] = 100,  ['type'] = 'item', ['image'] = 'yeast.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Moonshine Item'},
    ['corn']      = {['name'] = 'corn',      ['label'] = 'Corn',      ['weight'] = 100,  ['type'] = 'item', ['image'] = 'corn.png',      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Moonshine Item'},
    ['water']     = {['name'] = 'water',     ['label'] = 'Water',     ['weight'] = 100,  ['type'] = 'item', ['image'] = 'water.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Moonshine Item'},
    ['sugar']     = {['name'] = 'sugar',     ['label'] = 'Sugar',     ['weight'] = 100,  ['type'] = 'item', ['image'] = 'sugar.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Moonshine Item'},
    ['mash']      = {['name'] = 'mash',      ['label'] = 'Mash',      ['weight'] = 1000, ['type'] = 'item', ['image'] = 'mash.png',      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Moonshine Item'},
    ['jug']       = {['name'] = 'jug',       ['label'] = 'Jug',       ['weight'] = 300,  ['type'] = 'item', ['image'] = 'jug.png',       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Moonshine Item'},

    -- crafting
    ['nails']    = {['name'] = 'nails',    ['label'] = 'Nails',    ['weight'] = 100, ['type'] = 'item', ['image'] = 'nails.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used with crafting'},
    ['copper']   = {['name'] = 'copper',   ['label'] = 'Copper',   ['weight'] = 100, ['type'] = 'item', ['image'] = 'copper.png',   ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used with crafting'},
    ['aluminum'] = {['name'] = 'aluminum', ['label'] = 'Aluminum', ['weight'] = 100, ['type'] = 'item', ['image'] = 'aluminum.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used with crafting'},
    ['iron']     = {['name'] = 'iron',     ['label'] = 'Iron',     ['weight'] = 100, ['type'] = 'item', ['image'] = 'iron.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used with crafting'},
    ['steel']    = {['name'] = 'steel',    ['label'] = 'Steel',    ['weight'] = 100, ['type'] = 'item', ['image'] = 'steel.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used with crafting'},
    ['wood']     = {['name'] = 'wood',     ['label'] = 'Wood',     ['weight'] = 100, ['type'] = 'item', ['image'] = 'wood.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used with crafting'},
    ['pickaxe']  = {['name'] = 'pickaxe',  ['label'] = 'PickAxe',  ['weight'] = 100, ['type'] = 'item', ['image'] = 'pickaxe.png',  ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'equipment'},

    -- cooking
    ['cooked_fish'] = {['name'] = 'cooked_fish', ['label'] = 'Cooked Fish', ['weight'] = 100, ['type'] = 'item', ['image'] = 'cooked_fish.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used with cooking'},
    ['cooked_meat'] = {['name'] = 'cooked_meat', ['label'] = 'Cooked Meat', ['weight'] = 100, ['type'] = 'item', ['image'] = 'cooked_meat.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used with cooking'},
    ['raw_fish']    = {['name'] = 'raw_fish',    ['label'] = 'Raw Fish',    ['weight'] = 100, ['type'] = 'item', ['image'] = 'raw_fish.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used with cooking'},
    ['raw_meat']    = {['name'] = 'raw_meat',    ['label'] = 'Raw Meat',    ['weight'] = 100, ['type'] = 'item', ['image'] = 'raw_meat.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used with cooking'},
    ['coal']        = {['name'] = 'coal',        ['label'] = 'Coal',        ['weight'] = 100, ['type'] = 'item', ['image'] = 'coal.png',        ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used with cooking'},

    -- for robbery
    ['lockpick'] = {['name'] = 'lockpick', ['label'] = 'Lockpick', ['weight'] = 100, ['type'] = 'item', ['image'] = 'lockpick.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'for picking locks'},